// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (email, password_hash, role, application_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, application_id, status, last_login_at, created_at, updated_at, token_version
`

type CreateAdminUserParams struct {
	Email         string      `json:"email"`
	PasswordHash  string      `json:"password_hash"`
	Role          AdminRole   `json:"role"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.ApplicationID,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ApplicationID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, email, password_hash, role, application_id, status, last_login_at, created_at, updated_at, token_version FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminUser(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUser, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ApplicationID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, password_hash, role, application_id, status, last_login_at, created_at, updated_at, token_version FROM admin_users WHERE email = $1
`

// Usada por el login del panel (Fase 2).
func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ApplicationID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const incrementAdminTokenVersion = `-- name: IncrementAdminTokenVersion :one
UPDATE admin_users SET token_version = token_version + 1 WHERE id = $1
RETURNING token_version
`

// Invalida todos los refresh tokens del admin (logout / revocación).
func (q *Queries) IncrementAdminTokenVersion(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementAdminTokenVersion, id)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, password_hash, role, application_id, status, last_login_at, created_at, updated_at, token_version FROM admin_users ORDER BY created_at DESC
`

func (q *Queries) ListAdminUsers(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminUser
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.ApplicationID,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdminUserStatus = `-- name: SetAdminUserStatus :one
UPDATE admin_users SET status = $2 WHERE id = $1
RETURNING id, email, password_hash, role, application_id, status, last_login_at, created_at, updated_at, token_version
`

type SetAdminUserStatusParams struct {
	ID     uuid.UUID            `json:"id"`
	Status StatusActiveDisabled `json:"status"`
}

func (q *Queries) SetAdminUserStatus(ctx context.Context, arg SetAdminUserStatusParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, setAdminUserStatus, arg.ID, arg.Status)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ApplicationID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const touchAdminLastLogin = `-- name: TouchAdminLastLogin :exec
UPDATE admin_users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAdminLastLogin, id)
	return err
}
