// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO admin_audit_logs (
    actor_admin_id, application_id, action, target_type, target_id, details, ip, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, actor_admin_id, application_id, action, target_type, target_id, details, ip, user_agent, created_at
`

type CreateAuditLogParams struct {
	ActorAdminID  uuid.UUID   `json:"actor_admin_id"`
	ApplicationID pgtype.UUID `json:"application_id"`
	Action        string      `json:"action"`
	TargetType    string      `json:"target_type"`
	TargetID      *string     `json:"target_id"`
	Details       []byte      `json:"details"`
	Ip            *string     `json:"ip"`
	UserAgent     *string     `json:"user_agent"`
}

// Registra una acción del panel de administración. Se invoca dentro de la misma
// transacción que la acción mutante (ver internal/audit). Usado desde la Fase 6.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorAdminID,
		arg.ApplicationID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.Ip,
		arg.UserAgent,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorAdminID,
		&i.ApplicationID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Details,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByApplication = `-- name: ListAuditLogsByApplication :many
SELECT id, actor_admin_id, application_id, action, target_type, target_id, details, ip, user_agent, created_at FROM admin_audit_logs
WHERE application_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByApplicationParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByApplication(ctx context.Context, arg ListAuditLogsByApplicationParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByApplication, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorAdminID,
			&i.ApplicationID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
