// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (application_id, key_id, secret_enc, scopes, expires_at, name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, key_id, secret_enc, scopes, status, last_used_at, expires_at, created_at, name
`

type CreateAPIKeyParams struct {
	ApplicationID uuid.UUID          `json:"application_id"`
	KeyID         string             `json:"key_id"`
	SecretEnc     []byte             `json:"secret_enc"`
	Scopes        []string           `json:"scopes"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	Name          string             `json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ApplicationID,
		arg.KeyID,
		arg.SecretEnc,
		arg.Scopes,
		arg.ExpiresAt,
		arg.Name,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.KeyID,
		&i.SecretEnc,
		&i.Scopes,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND application_id = $2
`

type DeleteAPIKeyParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Borrado real (la revocación solo la desactiva). Sirve para limpiar la lista de
// keys revocadas, que si no se acumulan sin poder quitarlas. El handler exige que
// la key esté ya REVOKED: así no se puede borrar por error una key en uso.
func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.ApplicationID)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, application_id, key_id, secret_enc, scopes, status, last_used_at, expires_at, created_at, name FROM api_keys WHERE id = $1 AND application_id = $2
`

type GetAPIKeyParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.ApplicationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.KeyID,
		&i.SecretEnc,
		&i.Scopes,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getAPIKeyByKeyID = `-- name: GetAPIKeyByKeyID :one
SELECT id, application_id, key_id, secret_enc, scopes, status, last_used_at, expires_at, created_at, name FROM api_keys WHERE key_id = $1
`

// Usada por la autenticación HMAC (Fase 2): localiza la credencial por su id
// público para recalcular la firma.
func (q *Queries) GetAPIKeyByKeyID(ctx context.Context, keyID string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKeyID, keyID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.KeyID,
		&i.SecretEnc,
		&i.Scopes,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const listAPIKeysByApplication = `-- name: ListAPIKeysByApplication :many
SELECT id, application_id, key_id, secret_enc, scopes, status, last_used_at, expires_at, created_at, name FROM api_keys WHERE application_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByApplication(ctx context.Context, applicationID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.KeyID,
			&i.SecretEnc,
			&i.Scopes,
			&i.Status,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET status = 'REVOKED'
WHERE id = $1 AND application_id = $2
`

type RevokeAPIKeyParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.ApplicationID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
