// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota
`

type CreateApplicationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.Name, arg.Slug)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}

const getApplicationBySlug = `-- name: GetApplicationBySlug :one
SELECT id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota FROM applications WHERE slug = $1
`

func (q *Queries) GetApplicationBySlug(ctx context.Context, slug string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationBySlug, slug)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota FROM applications ORDER BY created_at DESC
`

func (q *Queries) ListApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PiiRetentionDays,
			&i.DailySendQuota,
			&i.MonthlySendQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationQuota = `-- name: SetApplicationQuota :one
UPDATE applications SET daily_send_quota = $2, monthly_send_quota = $3 WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota
`

type SetApplicationQuotaParams struct {
	ID               uuid.UUID `json:"id"`
	DailySendQuota   int32     `json:"daily_send_quota"`
	MonthlySendQuota int32     `json:"monthly_send_quota"`
}

func (q *Queries) SetApplicationQuota(ctx context.Context, arg SetApplicationQuotaParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationQuota, arg.ID, arg.DailySendQuota, arg.MonthlySendQuota)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}

const setApplicationRetention = `-- name: SetApplicationRetention :one
UPDATE applications SET pii_retention_days = $2 WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota
`

type SetApplicationRetentionParams struct {
	ID               uuid.UUID `json:"id"`
	PiiRetentionDays int32     `json:"pii_retention_days"`
}

func (q *Queries) SetApplicationRetention(ctx context.Context, arg SetApplicationRetentionParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationRetention, arg.ID, arg.PiiRetentionDays)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}

const setApplicationStatus = `-- name: SetApplicationStatus :one
UPDATE applications SET status = $2 WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota
`

type SetApplicationStatusParams struct {
	ID     uuid.UUID             `json:"id"`
	Status StatusActiveSuspended `json:"status"`
}

func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationStatus, arg.ID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications SET name = $2 WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota
`

type UpdateApplicationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication, arg.ID, arg.Name)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}

const updateApplicationSlug = `-- name: UpdateApplicationSlug :one
UPDATE applications SET slug = $2 WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, pii_retention_days, daily_send_quota, monthly_send_quota
`

type UpdateApplicationSlugParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

// El slug es UNIQUE. Cambiarlo es seguro para los clientes HMAC (autentican por
// key_id -> application_id, nunca por slug). Un duplicado viola la constraint y
// el handler lo traduce a 409.
func (q *Queries) UpdateApplicationSlug(ctx context.Context, arg UpdateApplicationSlugParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationSlug, arg.ID, arg.Slug)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PiiRetentionDays,
		&i.DailySendQuota,
		&i.MonthlySendQuota,
	)
	return i, err
}
