// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: base_templates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getBaseTemplate = `-- name: GetBaseTemplate :one
SELECT id, key, channel, category, name, description, structure, suggested_variables, is_active, created_at, updated_at, kind, body, subject FROM base_templates WHERE id = $1
`

func (q *Queries) GetBaseTemplate(ctx context.Context, id uuid.UUID) (BaseTemplate, error) {
	row := q.db.QueryRow(ctx, getBaseTemplate, id)
	var i BaseTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Channel,
		&i.Category,
		&i.Name,
		&i.Description,
		&i.Structure,
		&i.SuggestedVariables,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Body,
		&i.Subject,
	)
	return i, err
}

const getBaseTemplateByKey = `-- name: GetBaseTemplateByKey :one
SELECT id, key, channel, category, name, description, structure, suggested_variables, is_active, created_at, updated_at, kind, body, subject FROM base_templates WHERE key = $1
`

func (q *Queries) GetBaseTemplateByKey(ctx context.Context, key string) (BaseTemplate, error) {
	row := q.db.QueryRow(ctx, getBaseTemplateByKey, key)
	var i BaseTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Channel,
		&i.Category,
		&i.Name,
		&i.Description,
		&i.Structure,
		&i.SuggestedVariables,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Body,
		&i.Subject,
	)
	return i, err
}

const listBaseTemplates = `-- name: ListBaseTemplates :many
SELECT id, key, channel, category, name, description, structure, suggested_variables, is_active, created_at, updated_at, kind, body, subject FROM base_templates
WHERE is_active = true
ORDER BY category, key
`

func (q *Queries) ListBaseTemplates(ctx context.Context) ([]BaseTemplate, error) {
	rows, err := q.db.Query(ctx, listBaseTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BaseTemplate
	for rows.Next() {
		var i BaseTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Channel,
			&i.Category,
			&i.Name,
			&i.Description,
			&i.Structure,
			&i.SuggestedVariables,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Body,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
