// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_providers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createChannelProvider = `-- name: CreateChannelProvider :one
INSERT INTO channel_providers (application_id, channel, provider, name, config_enc)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, application_id, channel, provider, name, config_enc, status, created_at, updated_at
`

type CreateChannelProviderParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Channel       Channel   `json:"channel"`
	Provider      string    `json:"provider"`
	Name          string    `json:"name"`
	ConfigEnc     []byte    `json:"config_enc"`
}

func (q *Queries) CreateChannelProvider(ctx context.Context, arg CreateChannelProviderParams) (ChannelProvider, error) {
	row := q.db.QueryRow(ctx, createChannelProvider,
		arg.ApplicationID,
		arg.Channel,
		arg.Provider,
		arg.Name,
		arg.ConfigEnc,
	)
	var i ChannelProvider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Channel,
		&i.Provider,
		&i.Name,
		&i.ConfigEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelProvider = `-- name: DeleteChannelProvider :exec
DELETE FROM channel_providers WHERE id = $1 AND application_id = $2
`

type DeleteChannelProviderParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteChannelProvider(ctx context.Context, arg DeleteChannelProviderParams) error {
	_, err := q.db.Exec(ctx, deleteChannelProvider, arg.ID, arg.ApplicationID)
	return err
}

const getChannelProvider = `-- name: GetChannelProvider :one
SELECT id, application_id, channel, provider, name, config_enc, status, created_at, updated_at FROM channel_providers
WHERE id = $1 AND application_id = $2
`

type GetChannelProviderParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) GetChannelProvider(ctx context.Context, arg GetChannelProviderParams) (ChannelProvider, error) {
	row := q.db.QueryRow(ctx, getChannelProvider, arg.ID, arg.ApplicationID)
	var i ChannelProvider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Channel,
		&i.Provider,
		&i.Name,
		&i.ConfigEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelProviders = `-- name: ListChannelProviders :many
SELECT id, application_id, channel, provider, name, config_enc, status, created_at, updated_at FROM channel_providers
WHERE application_id = $1 ORDER BY name
`

func (q *Queries) ListChannelProviders(ctx context.Context, applicationID uuid.UUID) ([]ChannelProvider, error) {
	rows, err := q.db.Query(ctx, listChannelProviders, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelProvider
	for rows.Next() {
		var i ChannelProvider
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Channel,
			&i.Provider,
			&i.Name,
			&i.ConfigEnc,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelProvider = `-- name: UpdateChannelProvider :one
UPDATE channel_providers SET
    channel = $3, provider = $4, name = $5, config_enc = $6, status = $7
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, channel, provider, name, config_enc, status, created_at, updated_at
`

type UpdateChannelProviderParams struct {
	ID            uuid.UUID            `json:"id"`
	ApplicationID uuid.UUID            `json:"application_id"`
	Channel       Channel              `json:"channel"`
	Provider      string               `json:"provider"`
	Name          string               `json:"name"`
	ConfigEnc     []byte               `json:"config_enc"`
	Status        StatusActiveDisabled `json:"status"`
}

func (q *Queries) UpdateChannelProvider(ctx context.Context, arg UpdateChannelProviderParams) (ChannelProvider, error) {
	row := q.db.QueryRow(ctx, updateChannelProvider,
		arg.ID,
		arg.ApplicationID,
		arg.Channel,
		arg.Provider,
		arg.Name,
		arg.ConfigEnc,
		arg.Status,
	)
	var i ChannelProvider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Channel,
		&i.Provider,
		&i.Name,
		&i.ConfigEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
