// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_routes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChannelRoute = `-- name: CreateChannelRoute :one
INSERT INTO channel_routes
    (application_id, notification_type, channel, template_key, smtp_connection_id, channel_provider_id,
     send_priority, pii_retention_days, retention_days)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, application_id, notification_type, channel, smtp_connection_id, channel_provider_id, created_at, updated_at, template_key, send_priority, pii_retention_days, retention_days
`

type CreateChannelRouteParams struct {
	ApplicationID     uuid.UUID   `json:"application_id"`
	NotificationType  string      `json:"notification_type"`
	Channel           Channel     `json:"channel"`
	TemplateKey       *string     `json:"template_key"`
	SmtpConnectionID  pgtype.UUID `json:"smtp_connection_id"`
	ChannelProviderID pgtype.UUID `json:"channel_provider_id"`
	SendPriority      Priority    `json:"send_priority"`
	PiiRetentionDays  *int32      `json:"pii_retention_days"`
	RetentionDays     *int32      `json:"retention_days"`
}

func (q *Queries) CreateChannelRoute(ctx context.Context, arg CreateChannelRouteParams) (ChannelRoute, error) {
	row := q.db.QueryRow(ctx, createChannelRoute,
		arg.ApplicationID,
		arg.NotificationType,
		arg.Channel,
		arg.TemplateKey,
		arg.SmtpConnectionID,
		arg.ChannelProviderID,
		arg.SendPriority,
		arg.PiiRetentionDays,
		arg.RetentionDays,
	)
	var i ChannelRoute
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.NotificationType,
		&i.Channel,
		&i.SmtpConnectionID,
		&i.ChannelProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateKey,
		&i.SendPriority,
		&i.PiiRetentionDays,
		&i.RetentionDays,
	)
	return i, err
}

const deleteChannelRoute = `-- name: DeleteChannelRoute :exec
DELETE FROM channel_routes WHERE id = $1 AND application_id = $2
`

type DeleteChannelRouteParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteChannelRoute(ctx context.Context, arg DeleteChannelRouteParams) error {
	_, err := q.db.Exec(ctx, deleteChannelRoute, arg.ID, arg.ApplicationID)
	return err
}

const getChannelRouteByID = `-- name: GetChannelRouteByID :one
SELECT id, application_id, notification_type, channel, smtp_connection_id, channel_provider_id, created_at, updated_at, template_key, send_priority, pii_retention_days, retention_days FROM channel_routes
WHERE id = $1 AND application_id = $2
`

type GetChannelRouteByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Resuelve el "Tipo de notificación" por id (dentro de la app).
func (q *Queries) GetChannelRouteByID(ctx context.Context, arg GetChannelRouteByIDParams) (ChannelRoute, error) {
	row := q.db.QueryRow(ctx, getChannelRouteByID, arg.ID, arg.ApplicationID)
	var i ChannelRoute
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.NotificationType,
		&i.Channel,
		&i.SmtpConnectionID,
		&i.ChannelProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateKey,
		&i.SendPriority,
		&i.PiiRetentionDays,
		&i.RetentionDays,
	)
	return i, err
}

const getChannelRouteByName = `-- name: GetChannelRouteByName :one
SELECT id, application_id, notification_type, channel, smtp_connection_id, channel_provider_id, created_at, updated_at, template_key, send_priority, pii_retention_days, retention_days FROM channel_routes
WHERE application_id = $1 AND notification_type = $2
`

type GetChannelRouteByNameParams struct {
	ApplicationID    uuid.UUID `json:"application_id"`
	NotificationType string    `json:"notification_type"`
}

// Resuelve el "Tipo de notificación" por su nombre único (notification_type).
func (q *Queries) GetChannelRouteByName(ctx context.Context, arg GetChannelRouteByNameParams) (ChannelRoute, error) {
	row := q.db.QueryRow(ctx, getChannelRouteByName, arg.ApplicationID, arg.NotificationType)
	var i ChannelRoute
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.NotificationType,
		&i.Channel,
		&i.SmtpConnectionID,
		&i.ChannelProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateKey,
		&i.SendPriority,
		&i.PiiRetentionDays,
		&i.RetentionDays,
	)
	return i, err
}

const listChannelRoutes = `-- name: ListChannelRoutes :many
SELECT id, application_id, notification_type, channel, smtp_connection_id, channel_provider_id, created_at, updated_at, template_key, send_priority, pii_retention_days, retention_days FROM channel_routes
WHERE application_id = $1
ORDER BY notification_type, channel
`

func (q *Queries) ListChannelRoutes(ctx context.Context, applicationID uuid.UUID) ([]ChannelRoute, error) {
	rows, err := q.db.Query(ctx, listChannelRoutes, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelRoute
	for rows.Next() {
		var i ChannelRoute
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.NotificationType,
			&i.Channel,
			&i.SmtpConnectionID,
			&i.ChannelProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateKey,
			&i.SendPriority,
			&i.PiiRetentionDays,
			&i.RetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesForResolution = `-- name: ListRoutesForResolution :many
SELECT id, application_id, notification_type, channel, smtp_connection_id, channel_provider_id, created_at, updated_at, template_key, send_priority, pii_retention_days, retention_days FROM channel_routes
WHERE application_id = $1 AND notification_type = $2 AND channel = $3
`

type ListRoutesForResolutionParams struct {
	ApplicationID    uuid.UUID `json:"application_id"`
	NotificationType string    `json:"notification_type"`
	Channel          Channel   `json:"channel"`
}

// Ruta(s) para (app, tipo, canal). Con el modelo 1:1 devuelve como mucho una,
// pero se mantiene :many para no romper la resolución del procesador.
func (q *Queries) ListRoutesForResolution(ctx context.Context, arg ListRoutesForResolutionParams) ([]ChannelRoute, error) {
	rows, err := q.db.Query(ctx, listRoutesForResolution, arg.ApplicationID, arg.NotificationType, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelRoute
	for rows.Next() {
		var i ChannelRoute
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.NotificationType,
			&i.Channel,
			&i.SmtpConnectionID,
			&i.ChannelProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateKey,
			&i.SendPriority,
			&i.PiiRetentionDays,
			&i.RetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelRouteSettings = `-- name: UpdateChannelRouteSettings :one
UPDATE channel_routes
SET send_priority = $3, pii_retention_days = $4, retention_days = $5
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, notification_type, channel, smtp_connection_id, channel_provider_id, created_at, updated_at, template_key, send_priority, pii_retention_days, retention_days
`

type UpdateChannelRouteSettingsParams struct {
	ID               uuid.UUID `json:"id"`
	ApplicationID    uuid.UUID `json:"application_id"`
	SendPriority     Priority  `json:"send_priority"`
	PiiRetentionDays *int32    `json:"pii_retention_days"`
	RetentionDays    *int32    `json:"retention_days"`
}

// Ajustes operables del Tipo (prioridad y retención); el resto se recrea.
// Los NULL en retención son valores válidos (heredar / no borrar), no "sin cambio".
func (q *Queries) UpdateChannelRouteSettings(ctx context.Context, arg UpdateChannelRouteSettingsParams) (ChannelRoute, error) {
	row := q.db.QueryRow(ctx, updateChannelRouteSettings,
		arg.ID,
		arg.ApplicationID,
		arg.SendPriority,
		arg.PiiRetentionDays,
		arg.RetentionDays,
	)
	var i ChannelRoute
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.NotificationType,
		&i.Channel,
		&i.SmtpConnectionID,
		&i.ChannelProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateKey,
		&i.SendPriority,
		&i.PiiRetentionDays,
		&i.RetentionDays,
	)
	return i, err
}
