// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_attempts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO delivery_attempts (notification_id, attempt_number, asynq_task_id, status)
VALUES ($1, $2, $3, 'PROCESSING')
RETURNING id, notification_id, attempt_number, asynq_task_id, status, provider_ref, error_code, error_message, started_at, finished_at
`

type CreateDeliveryAttemptParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	AttemptNumber  int32     `json:"attempt_number"`
	AsynqTaskID    *string   `json:"asynq_task_id"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt, arg.NotificationID, arg.AttemptNumber, arg.AsynqTaskID)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.AttemptNumber,
		&i.AsynqTaskID,
		&i.Status,
		&i.ProviderRef,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishDeliveryAttempt = `-- name: FinishDeliveryAttempt :exec
UPDATE delivery_attempts
SET status = $2, provider_ref = $3, error_code = $4, error_message = $5, finished_at = now()
WHERE id = $1
`

type FinishDeliveryAttemptParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       DeliveryStatus `json:"status"`
	ProviderRef  *string        `json:"provider_ref"`
	ErrorCode    *string        `json:"error_code"`
	ErrorMessage *string        `json:"error_message"`
}

func (q *Queries) FinishDeliveryAttempt(ctx context.Context, arg FinishDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, finishDeliveryAttempt,
		arg.ID,
		arg.Status,
		arg.ProviderRef,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	return err
}

const hasSuccessfulDeliveryAttempt = `-- name: HasSuccessfulDeliveryAttempt :one
SELECT EXISTS (
    SELECT 1 FROM delivery_attempts
    WHERE notification_id = $1 AND status = 'SUCCESS'
) AS sent
`

// Guardia anti-duplicado del worker: con at-least-once, una reentrega tras un
// crash post-envío reenviaría de verdad; si ya hay un intento SUCCESS, el
// mensaje YA llegó y solo falta marcar SENT.
func (q *Queries) HasSuccessfulDeliveryAttempt(ctx context.Context, notificationID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSuccessfulDeliveryAttempt, notificationID)
	var sent bool
	err := row.Scan(&sent)
	return sent, err
}

const listDeliveryAttemptsByNotification = `-- name: ListDeliveryAttemptsByNotification :many
SELECT id, notification_id, attempt_number, asynq_task_id, status, provider_ref, error_code, error_message, started_at, finished_at FROM delivery_attempts
WHERE notification_id = $1
ORDER BY attempt_number
`

func (q *Queries) ListDeliveryAttemptsByNotification(ctx context.Context, notificationID uuid.UUID) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttemptsByNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.AttemptNumber,
			&i.AsynqTaskID,
			&i.Status,
			&i.ProviderRef,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
