// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminRole string

const (
	AdminRoleSUPERADMIN AdminRole = "SUPER_ADMIN"
	AdminRoleAPPADMIN   AdminRole = "APP_ADMIN"
)

func (e *AdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRole(s)
	case string:
		*e = AdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRole: %T", src)
	}
	return nil
}

type NullAdminRole struct {
	AdminRole AdminRole `json:"admin_role"`
	Valid     bool      `json:"valid"` // Valid is true if AdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRole), nil
}

type Channel string

const (
	ChannelEMAIL Channel = "EMAIL"
	ChannelPUSH  Channel = "PUSH"
	ChannelSMS   Channel = "SMS"
	ChannelINAPP Channel = "IN_APP"
)

func (e *Channel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Channel(s)
	case string:
		*e = Channel(s)
	default:
		return fmt.Errorf("unsupported scan type for Channel: %T", src)
	}
	return nil
}

type NullChannel struct {
	Channel Channel `json:"channel"`
	Valid   bool    `json:"valid"` // Valid is true if Channel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannel) Scan(value interface{}) error {
	if value == nil {
		ns.Channel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Channel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Channel), nil
}

type DeliveryStatus string

const (
	DeliveryStatusPROCESSING DeliveryStatus = "PROCESSING"
	DeliveryStatusSUCCESS    DeliveryStatus = "SUCCESS"
	DeliveryStatusFAILED     DeliveryStatus = "FAILED"
	DeliveryStatusRETRY      DeliveryStatus = "RETRY"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type NotificationStatus string

const (
	NotificationStatusPENDING    NotificationStatus = "PENDING"
	NotificationStatusQUEUED     NotificationStatus = "QUEUED"
	NotificationStatusPROCESSING NotificationStatus = "PROCESSING"
	NotificationStatusSENT       NotificationStatus = "SENT"
	NotificationStatusDELIVERED  NotificationStatus = "DELIVERED"
	NotificationStatusREAD       NotificationStatus = "READ"
	NotificationStatusFAILED     NotificationStatus = "FAILED"
	NotificationStatusCANCELLED  NotificationStatus = "CANCELLED"
	NotificationStatusBOUNCED    NotificationStatus = "BOUNCED"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus `json:"notification_status"`
	Valid              bool               `json:"valid"` // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type Priority string

const (
	PriorityLOW    Priority = "LOW"
	PriorityNORMAL Priority = "NORMAL"
	PriorityHIGH   Priority = "HIGH"
	PriorityURGENT Priority = "URGENT"
)

func (e *Priority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Priority(s)
	case string:
		*e = Priority(s)
	default:
		return fmt.Errorf("unsupported scan type for Priority: %T", src)
	}
	return nil
}

type NullPriority struct {
	Priority Priority `json:"priority"`
	Valid    bool     `json:"valid"` // Valid is true if Priority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriority) Scan(value interface{}) error {
	if value == nil {
		ns.Priority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Priority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Priority), nil
}

type StatusActiveDisabled string

const (
	StatusActiveDisabledACTIVE   StatusActiveDisabled = "ACTIVE"
	StatusActiveDisabledDISABLED StatusActiveDisabled = "DISABLED"
)

func (e *StatusActiveDisabled) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusActiveDisabled(s)
	case string:
		*e = StatusActiveDisabled(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusActiveDisabled: %T", src)
	}
	return nil
}

type NullStatusActiveDisabled struct {
	StatusActiveDisabled StatusActiveDisabled `json:"status_active_disabled"`
	Valid                bool                 `json:"valid"` // Valid is true if StatusActiveDisabled is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusActiveDisabled) Scan(value interface{}) error {
	if value == nil {
		ns.StatusActiveDisabled, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusActiveDisabled.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusActiveDisabled) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusActiveDisabled), nil
}

type StatusActiveRevoked string

const (
	StatusActiveRevokedACTIVE  StatusActiveRevoked = "ACTIVE"
	StatusActiveRevokedREVOKED StatusActiveRevoked = "REVOKED"
)

func (e *StatusActiveRevoked) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusActiveRevoked(s)
	case string:
		*e = StatusActiveRevoked(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusActiveRevoked: %T", src)
	}
	return nil
}

type NullStatusActiveRevoked struct {
	StatusActiveRevoked StatusActiveRevoked `json:"status_active_revoked"`
	Valid               bool                `json:"valid"` // Valid is true if StatusActiveRevoked is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusActiveRevoked) Scan(value interface{}) error {
	if value == nil {
		ns.StatusActiveRevoked, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusActiveRevoked.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusActiveRevoked) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusActiveRevoked), nil
}

type StatusActiveSuspended string

const (
	StatusActiveSuspendedACTIVE    StatusActiveSuspended = "ACTIVE"
	StatusActiveSuspendedSUSPENDED StatusActiveSuspended = "SUSPENDED"
)

func (e *StatusActiveSuspended) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusActiveSuspended(s)
	case string:
		*e = StatusActiveSuspended(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusActiveSuspended: %T", src)
	}
	return nil
}

type NullStatusActiveSuspended struct {
	StatusActiveSuspended StatusActiveSuspended `json:"status_active_suspended"`
	Valid                 bool                  `json:"valid"` // Valid is true if StatusActiveSuspended is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusActiveSuspended) Scan(value interface{}) error {
	if value == nil {
		ns.StatusActiveSuspended, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusActiveSuspended.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusActiveSuspended) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusActiveSuspended), nil
}

type AdminAuditLog struct {
	ID            uuid.UUID          `json:"id"`
	ActorAdminID  uuid.UUID          `json:"actor_admin_id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Action        string             `json:"action"`
	TargetType    string             `json:"target_type"`
	TargetID      *string            `json:"target_id"`
	Details       []byte             `json:"details"`
	Ip            *string            `json:"ip"`
	UserAgent     *string            `json:"user_agent"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AdminUser struct {
	ID            uuid.UUID            `json:"id"`
	Email         string               `json:"email"`
	PasswordHash  string               `json:"password_hash"`
	Role          AdminRole            `json:"role"`
	ApplicationID pgtype.UUID          `json:"application_id"`
	Status        StatusActiveDisabled `json:"status"`
	LastLoginAt   pgtype.Timestamptz   `json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `json:"updated_at"`
	TokenVersion  int32                `json:"token_version"`
}

type ApiKey struct {
	ID            uuid.UUID           `json:"id"`
	ApplicationID uuid.UUID           `json:"application_id"`
	KeyID         string              `json:"key_id"`
	SecretEnc     []byte              `json:"secret_enc"`
	Scopes        []string            `json:"scopes"`
	Status        StatusActiveRevoked `json:"status"`
	LastUsedAt    pgtype.Timestamptz  `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz  `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	Name          string              `json:"name"`
}

type Application struct {
	ID               uuid.UUID             `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Status           StatusActiveSuspended `json:"status"`
	CreatedAt        pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz    `json:"updated_at"`
	PiiRetentionDays int32                 `json:"pii_retention_days"`
	DailySendQuota   int32                 `json:"daily_send_quota"`
	MonthlySendQuota int32                 `json:"monthly_send_quota"`
}

type BaseTemplate struct {
	ID                 uuid.UUID          `json:"id"`
	Key                string             `json:"key"`
	Channel            Channel            `json:"channel"`
	Category           string             `json:"category"`
	Name               string             `json:"name"`
	Description        *string            `json:"description"`
	Structure          json.RawMessage    `json:"structure"`
	SuggestedVariables []byte             `json:"suggested_variables"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Kind               string             `json:"kind"`
	Body               *string            `json:"body"`
	Subject            *string            `json:"subject"`
}

type ChannelProvider struct {
	ID            uuid.UUID            `json:"id"`
	ApplicationID uuid.UUID            `json:"application_id"`
	Channel       Channel              `json:"channel"`
	Provider      string               `json:"provider"`
	Name          string               `json:"name"`
	ConfigEnc     []byte               `json:"config_enc"`
	Status        StatusActiveDisabled `json:"status"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `json:"updated_at"`
}

type ChannelRoute struct {
	ID                uuid.UUID          `json:"id"`
	ApplicationID     uuid.UUID          `json:"application_id"`
	NotificationType  string             `json:"notification_type"`
	Channel           Channel            `json:"channel"`
	SmtpConnectionID  pgtype.UUID        `json:"smtp_connection_id"`
	ChannelProviderID pgtype.UUID        `json:"channel_provider_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TemplateKey       *string            `json:"template_key"`
	SendPriority      Priority           `json:"send_priority"`
	PiiRetentionDays  *int32             `json:"pii_retention_days"`
	RetentionDays     *int32             `json:"retention_days"`
}

type DeliveryAttempt struct {
	ID             uuid.UUID          `json:"id"`
	NotificationID uuid.UUID          `json:"notification_id"`
	AttemptNumber  int32              `json:"attempt_number"`
	AsynqTaskID    *string            `json:"asynq_task_id"`
	Status         DeliveryStatus     `json:"status"`
	ProviderRef    *string            `json:"provider_ref"`
	ErrorCode      *string            `json:"error_code"`
	ErrorMessage   *string            `json:"error_message"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Notification struct {
	ID               uuid.UUID          `json:"id"`
	ApplicationID    uuid.UUID          `json:"application_id"`
	TemplateKey      string             `json:"template_key"`
	TemplateVersion  *int32             `json:"template_version"`
	NotificationType string             `json:"notification_type"`
	Channel          Channel            `json:"channel"`
	RecipientUserID  *string            `json:"recipient_user_id"`
	Recipient        json.RawMessage    `json:"recipient"`
	Payload          json.RawMessage    `json:"payload"`
	Attachments      []byte             `json:"attachments"`
	Locale           *string            `json:"locale"`
	Priority         Priority           `json:"priority"`
	Status           NotificationStatus `json:"status"`
	IdempotencyKey   *string            `json:"idempotency_key"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	MaxRetries       int32              `json:"max_retries"`
	RetryCount       int32              `json:"retry_count"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
	FailedAt         pgtype.Timestamptz `json:"failed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
}

type NotificationLog struct {
	ID             uuid.UUID          `json:"id"`
	ApplicationID  uuid.UUID          `json:"application_id"`
	NotificationID pgtype.UUID        `json:"notification_id"`
	Event          string             `json:"event"`
	Message        *string            `json:"message"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RecurringSchedule struct {
	ID               uuid.UUID          `json:"id"`
	ApplicationID    uuid.UUID          `json:"application_id"`
	Name             string             `json:"name"`
	TemplateKey      string             `json:"template_key"`
	NotificationType string             `json:"notification_type"`
	Channel          Channel            `json:"channel"`
	Recipient        json.RawMessage    `json:"recipient"`
	RecipientUserID  *string            `json:"recipient_user_id"`
	Payload          json.RawMessage    `json:"payload"`
	Locale           *string            `json:"locale"`
	Priority         Priority           `json:"priority"`
	Cron             string             `json:"cron"`
	Enabled          bool               `json:"enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SmtpConnection struct {
	ID            uuid.UUID            `json:"id"`
	ApplicationID uuid.UUID            `json:"application_id"`
	Name          string               `json:"name"`
	Host          string               `json:"host"`
	Port          int32                `json:"port"`
	Username      string               `json:"username"`
	PasswordEnc   []byte               `json:"password_enc"`
	FromEmail     string               `json:"from_email"`
	FromName      string               `json:"from_name"`
	Secure        bool                 `json:"secure"`
	Status        StatusActiveDisabled `json:"status"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `json:"updated_at"`
}

type SuppressionList struct {
	ID            uuid.UUID          `json:"id"`
	ApplicationID uuid.UUID          `json:"application_id"`
	Channel       Channel            `json:"channel"`
	Recipient     string             `json:"recipient"`
	Reason        string             `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Template struct {
	ID                uuid.UUID          `json:"id"`
	ApplicationID     uuid.UUID          `json:"application_id"`
	Key               string             `json:"key"`
	Channel           Channel            `json:"channel"`
	BaseTemplateID    pgtype.UUID        `json:"base_template_id"`
	Name              string             `json:"name"`
	Description       *string            `json:"description"`
	Subject           *string            `json:"subject"`
	Structure         json.RawMessage    `json:"structure"`
	Body              string             `json:"body"`
	RequiredVariables []byte             `json:"required_variables"`
	Locale            string             `json:"locale"`
	Version           int32              `json:"version"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Kind              string             `json:"kind"`
}

type UserNotificationPreference struct {
	ID            uuid.UUID          `json:"id"`
	ApplicationID uuid.UUID          `json:"application_id"`
	UserID        string             `json:"user_id"`
	EmailEnabled  bool               `json:"email_enabled"`
	PushEnabled   bool               `json:"push_enabled"`
	SmsEnabled    bool               `json:"sms_enabled"`
	InAppEnabled  bool               `json:"in_app_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WebhookEndpoint struct {
	ID            uuid.UUID            `json:"id"`
	ApplicationID uuid.UUID            `json:"application_id"`
	Url           string               `json:"url"`
	SecretEnc     []byte               `json:"secret_enc"`
	Events        []string             `json:"events"`
	Status        StatusActiveDisabled `json:"status"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `json:"updated_at"`
}
