// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationLog = `-- name: CreateNotificationLog :exec
INSERT INTO notification_logs (application_id, notification_id, event, message, details)
VALUES ($1, $2, $3, $4, $5)
`

type CreateNotificationLogParams struct {
	ApplicationID  uuid.UUID   `json:"application_id"`
	NotificationID pgtype.UUID `json:"notification_id"`
	Event          string      `json:"event"`
	Message        *string     `json:"message"`
	Details        []byte      `json:"details"`
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error {
	_, err := q.db.Exec(ctx, createNotificationLog,
		arg.ApplicationID,
		arg.NotificationID,
		arg.Event,
		arg.Message,
		arg.Details,
	)
	return err
}

const listNotificationLogsByNotification = `-- name: ListNotificationLogsByNotification :many
SELECT id, application_id, notification_id, event, message, details, created_at FROM notification_logs
WHERE notification_id = $1
ORDER BY created_at
`

func (q *Queries) ListNotificationLogsByNotification(ctx context.Context, notificationID pgtype.UUID) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationLogsByNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationLog
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.NotificationID,
			&i.Event,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
