// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveNotification = `-- name: ArchiveNotification :one
UPDATE notifications
SET archived_at = COALESCE(archived_at, now())
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at
`

type ArchiveNotificationParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Archivar es una acción del DESTINATARIO y es ortogonal al estado de entrega:
// por eso es una columna y no un estado más (se archiva algo leído sin perder
// que fue leído). Idempotente: re-archivar no mueve la fecha.
func (q *Queries) ArchiveNotification(ctx context.Context, arg ArchiveNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, archiveNotification, arg.ID, arg.ApplicationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const archiveReadNotificationsByUser = `-- name: ArchiveReadNotificationsByUser :exec
UPDATE notifications
SET archived_at = now()
WHERE application_id = $1
  AND recipient_user_id = $2
  AND status = 'READ'
  AND archived_at IS NULL
`

type ArchiveReadNotificationsByUserParams struct {
	ApplicationID   uuid.UUID `json:"application_id"`
	RecipientUserID *string   `json:"recipient_user_id"`
}

// «Archivar todas las leídas» de un usuario: es la acción que de verdad limpia la
// bandeja. Scopeada por destinatario, así nunca puede tocar las de otro.
func (q *Queries) ArchiveReadNotificationsByUser(ctx context.Context, arg ArchiveReadNotificationsByUserParams) error {
	_, err := q.db.Exec(ctx, archiveReadNotificationsByUser, arg.ApplicationID, arg.RecipientUserID)
	return err
}

const cancelNotification = `-- name: CancelNotification :one
UPDATE notifications
SET status = 'CANCELLED'
WHERE id = $1 AND application_id = $2
  AND status IN ('PENDING', 'QUEUED')
RETURNING id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at
`

type CancelNotificationParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Cancela una notificación si aún no se ha enviado. El worker, al tomar la
// tarea, verá CANCELLED y no enviará.
func (q *Queries) CancelNotification(ctx context.Context, arg CancelNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, cancelNotification, arg.ID, arg.ApplicationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countNotificationStates = `-- name: CountNotificationStates :many
SELECT status,
       (scheduled_at IS NOT NULL AND scheduled_at > now()) AS scheduled_future,
       count(*)::int AS count
FROM notifications
WHERE application_id = $1
GROUP BY status, scheduled_future
`

type CountNotificationStatesRow struct {
	Status          NotificationStatus `json:"status"`
	ScheduledFuture *bool              `json:"scheduled_future"`
	Count           int32              `json:"count"`
}

// Conteo por (estado, ¿programada a futuro?) para derivar los estados de cola
// del monitor (§8.3) con domain.DeriveQueueState.
func (q *Queries) CountNotificationStates(ctx context.Context, applicationID uuid.UUID) ([]CountNotificationStatesRow, error) {
	rows, err := q.db.Query(ctx, countNotificationStates, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountNotificationStatesRow
	for rows.Next() {
		var i CountNotificationStatesRow
		if err := rows.Scan(&i.Status, &i.ScheduledFuture, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotificationsByPriority = `-- name: CountNotificationsByPriority :many
SELECT priority, count(*)::int AS count
FROM notifications
WHERE application_id = $1
GROUP BY priority
`

type CountNotificationsByPriorityRow struct {
	Priority Priority `json:"priority"`
	Count    int32    `json:"count"`
}

func (q *Queries) CountNotificationsByPriority(ctx context.Context, applicationID uuid.UUID) ([]CountNotificationsByPriorityRow, error) {
	rows, err := q.db.Query(ctx, countNotificationsByPriority, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountNotificationsByPriorityRow
	for rows.Next() {
		var i CountNotificationsByPriorityRow
		if err := rows.Scan(&i.Priority, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    application_id, template_key, template_version, notification_type, channel,
    recipient_user_id, recipient, payload, attachments, locale, priority,
    status, idempotency_key, scheduled_at, expires_at, max_retries
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at
`

type CreateNotificationParams struct {
	ApplicationID    uuid.UUID          `json:"application_id"`
	TemplateKey      string             `json:"template_key"`
	TemplateVersion  *int32             `json:"template_version"`
	NotificationType string             `json:"notification_type"`
	Channel          Channel            `json:"channel"`
	RecipientUserID  *string            `json:"recipient_user_id"`
	Recipient        json.RawMessage    `json:"recipient"`
	Payload          json.RawMessage    `json:"payload"`
	Attachments      []byte             `json:"attachments"`
	Locale           *string            `json:"locale"`
	Priority         Priority           `json:"priority"`
	Status           NotificationStatus `json:"status"`
	IdempotencyKey   *string            `json:"idempotency_key"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	MaxRetries       int32              `json:"max_retries"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ApplicationID,
		arg.TemplateKey,
		arg.TemplateVersion,
		arg.NotificationType,
		arg.Channel,
		arg.RecipientUserID,
		arg.Recipient,
		arg.Payload,
		arg.Attachments,
		arg.Locale,
		arg.Priority,
		arg.Status,
		arg.IdempotencyKey,
		arg.ScheduledAt,
		arg.ExpiresAt,
		arg.MaxRetries,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at FROM notifications
WHERE id = $1 AND application_id = $2
`

type GetNotificationParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Lectura con scope de tenant: SIEMPRE filtra por application_id para que un
// tenant no pueda leer notificaciones de otro.
func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.ApplicationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at FROM notifications WHERE id = $1
`

// Lectura por el worker (proceso de confianza): no filtra por tenant porque el
// worker opera sobre un notificationId concreto sacado de la cola.
func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getNotificationByIdempotencyKey = `-- name: GetNotificationByIdempotencyKey :one
SELECT id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at FROM notifications
WHERE application_id = $1 AND idempotency_key = $2
`

type GetNotificationByIdempotencyKeyParams struct {
	ApplicationID  uuid.UUID `json:"application_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

// Soporta la idempotencia por tenant (Fase 3): si ya existe, se devuelve.
func (q *Queries) GetNotificationByIdempotencyKey(ctx context.Context, arg GetNotificationByIdempotencyKeyParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByIdempotencyKey, arg.ApplicationID, arg.IdempotencyKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listNotificationsByApplication = `-- name: ListNotificationsByApplication :many
SELECT id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at FROM notifications
WHERE application_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByApplicationParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) ListNotificationsByApplication(ctx context.Context, arg ListNotificationsByApplicationParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByApplication, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.NotificationType,
			&i.Channel,
			&i.RecipientUserID,
			&i.Recipient,
			&i.Payload,
			&i.Attachments,
			&i.Locale,
			&i.Priority,
			&i.Status,
			&i.IdempotencyKey,
			&i.ScheduledAt,
			&i.ExpiresAt,
			&i.MaxRetries,
			&i.RetryCount,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsCursor = `-- name: ListNotificationsCursor :many
SELECT id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at FROM notifications
WHERE application_id = $1
  AND (CASE WHEN $2::boolean IS TRUE
            THEN archived_at IS NOT NULL
            ELSE archived_at IS NULL END)
  AND ($3::notification_status IS NULL OR status = $3)
  AND ($4::channel IS NULL OR channel = $4)
  AND ($5::text IS NULL OR recipient_user_id = $5)
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
  AND (
        $8::timestamptz IS NULL
        OR created_at < $8
        OR (created_at = $8 AND id < $9)
      )
ORDER BY created_at DESC, id DESC
LIMIT $10
`

type ListNotificationsCursorParams struct {
	ApplicationID   uuid.UUID           `json:"application_id"`
	Archived        *bool               `json:"archived"`
	Status          *NotificationStatus `json:"status"`
	Channel         *Channel            `json:"channel"`
	RecipientUserID *string             `json:"recipient_user_id"`
	StartDate       pgtype.Timestamptz  `json:"start_date"`
	EndDate         pgtype.Timestamptz  `json:"end_date"`
	CursorCreated   pgtype.Timestamptz  `json:"cursor_created"`
	CursorID        pgtype.UUID         `json:"cursor_id"`
	PageLimit       int32               `json:"page_limit"`
}

// Listado con filtros opcionales y paginación por cursor (keyset sobre
// created_at, id). Los filtros nulos no se aplican. Pide LIMIT+1 para saber si
// hay más página.
// El filtro `archived` decide qué se ve: NULL/false = solo las activas (lo que
// pide la campana; si no, la bandeja sería una retortera), true = solo el
// archivo.
func (q *Queries) ListNotificationsCursor(ctx context.Context, arg ListNotificationsCursorParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsCursor,
		arg.ApplicationID,
		arg.Archived,
		arg.Status,
		arg.Channel,
		arg.RecipientUserID,
		arg.StartDate,
		arg.EndDate,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.NotificationType,
			&i.Channel,
			&i.RecipientUserID,
			&i.Recipient,
			&i.Payload,
			&i.Attachments,
			&i.Locale,
			&i.Priority,
			&i.Status,
			&i.IdempotencyKey,
			&i.ScheduledAt,
			&i.ExpiresAt,
			&i.MaxRetries,
			&i.RetryCount,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleNotificationsForRequeue = `-- name: ListStaleNotificationsForRequeue :many
SELECT id, application_id, priority, max_retries FROM notifications
WHERE status IN ('PENDING', 'QUEUED')
  AND (scheduled_at IS NULL OR scheduled_at <= now())
  AND updated_at < $1
ORDER BY updated_at
LIMIT $2
`

type ListStaleNotificationsForRequeueParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

type ListStaleNotificationsForRequeueRow struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
	Priority      Priority  `json:"priority"`
	MaxRetries    int32     `json:"max_retries"`
}

// Candidatas del reaper: PENDING/QUEUED sin transición reciente y sin
// programación futura (huérfanas del hueco commit-luego-encolar). Compara
// updated_at (lo refresca el trigger) para no pisar reintentos recientes.
func (q *Queries) ListStaleNotificationsForRequeue(ctx context.Context, arg ListStaleNotificationsForRequeueParams) ([]ListStaleNotificationsForRequeueRow, error) {
	rows, err := q.db.Query(ctx, listStaleNotificationsForRequeue, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleNotificationsForRequeueRow
	for rows.Next() {
		var i ListStaleNotificationsForRequeueRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Priority,
			&i.MaxRetries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleProcessingForReconcile = `-- name: ListStaleProcessingForReconcile :many
SELECT n.id, n.application_id, n.priority, n.max_retries,
       COALESCE((SELECT da.status::text FROM delivery_attempts da
         WHERE da.notification_id = n.id
         ORDER BY da.started_at DESC LIMIT 1), '')::text AS last_attempt_status
FROM notifications n
WHERE n.status = 'PROCESSING'
  AND n.updated_at < $1
ORDER BY n.updated_at
LIMIT $2
`

type ListStaleProcessingForReconcileParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

type ListStaleProcessingForReconcileRow struct {
	ID                uuid.UUID `json:"id"`
	ApplicationID     uuid.UUID `json:"application_id"`
	Priority          Priority  `json:"priority"`
	MaxRetries        int32     `json:"max_retries"`
	LastAttemptStatus string    `json:"last_attempt_status"`
}

// PROCESSING atascadas (crash a mitad de envío, o el mark SENT best-effort
// falló). El reaper las reconcilia contra su último intento: SUCCESS => el
// mensaje llegó, solo falta marcar SENT (reenviar duplicaría); si no, se
// reencola (EnqueueSend es idempotente por TaskID).
func (q *Queries) ListStaleProcessingForReconcile(ctx context.Context, arg ListStaleProcessingForReconcileParams) ([]ListStaleProcessingForReconcileRow, error) {
	rows, err := q.db.Query(ctx, listStaleProcessingForReconcile, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleProcessingForReconcileRow
	for rows.Next() {
		var i ListStaleProcessingForReconcileRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Priority,
			&i.MaxRetries,
			&i.LastAttemptStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationBounced = `-- name: MarkNotificationBounced :execrows
UPDATE notifications
SET status = 'BOUNCED', updated_at = now()
WHERE id = $1 AND application_id = $2 AND status IN ('SENT', 'DELIVERED')
`

type MarkNotificationBouncedParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Bounce/queja del proveedor: solo avanza desde SENT/DELIVERED (no pisa
// terminales ni retrocede estados de lectura).
func (q *Queries) MarkNotificationBounced(ctx context.Context, arg MarkNotificationBouncedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationBounced, arg.ID, arg.ApplicationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec
UPDATE notifications
SET status = 'DELIVERED', delivered_at = now(), updated_at = now()
WHERE id = $1 AND application_id = $2 AND status = 'SENT'
`

type MarkNotificationDeliveredParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Confirmación de entrega del proveedor (ingesta de eventos). Solo avanza desde
// SENT para no pisar estados terminales (FAILED/CANCELLED) ni retroceder.
func (q *Queries) MarkNotificationDelivered(ctx context.Context, arg MarkNotificationDeliveredParams) error {
	_, err := q.db.Exec(ctx, markNotificationDelivered, arg.ID, arg.ApplicationID)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications
SET status = 'FAILED', failed_at = now(), retry_count = $2
WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID         uuid.UUID `json:"id"`
	RetryCount int32     `json:"retry_count"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.RetryCount)
	return err
}

const markNotificationReadByID = `-- name: MarkNotificationReadByID :one
UPDATE notifications
SET status = 'READ', read_at = now()
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at
`

type MarkNotificationReadByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) MarkNotificationReadByID(ctx context.Context, arg MarkNotificationReadByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationReadByID, arg.ID, arg.ApplicationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const markNotificationRetry = `-- name: MarkNotificationRetry :exec
UPDATE notifications
SET status = 'QUEUED', retry_count = $2
WHERE id = $1
`

type MarkNotificationRetryParams struct {
	ID         uuid.UUID `json:"id"`
	RetryCount int32     `json:"retry_count"`
}

// Entre reintentos la notificación vuelve a la cola (QUEUED). El estado RETRY
// es propio de delivery_attempts, no de la notificación (ver §3).
func (q *Queries) MarkNotificationRetry(ctx context.Context, arg MarkNotificationRetryParams) error {
	_, err := q.db.Exec(ctx, markNotificationRetry, arg.ID, arg.RetryCount)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications
SET status = 'SENT', sent_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const requeueNotification = `-- name: RequeueNotification :exec
UPDATE notifications
SET status = 'QUEUED', failed_at = NULL
WHERE id = $1 AND application_id = $2
`

type RequeueNotificationParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

// Reintento manual: deja la notificación lista para reenviar (vuelve a QUEUED).
func (q *Queries) RequeueNotification(ctx context.Context, arg RequeueNotificationParams) error {
	_, err := q.db.Exec(ctx, requeueNotification, arg.ID, arg.ApplicationID)
	return err
}

const setNotificationStatusByID = `-- name: SetNotificationStatusByID :exec
UPDATE notifications SET status = $2 WHERE id = $1
`

type SetNotificationStatusByIDParams struct {
	ID     uuid.UUID          `json:"id"`
	Status NotificationStatus `json:"status"`
}

func (q *Queries) SetNotificationStatusByID(ctx context.Context, arg SetNotificationStatusByIDParams) error {
	_, err := q.db.Exec(ctx, setNotificationStatusByID, arg.ID, arg.Status)
	return err
}

const setNotificationTemplateVersion = `-- name: SetNotificationTemplateVersion :exec
UPDATE notifications SET template_version = $2
WHERE id = $1 AND application_id = $3
`

type SetNotificationTemplateVersionParams struct {
	ID              uuid.UUID `json:"id"`
	TemplateVersion *int32    `json:"template_version"`
	ApplicationID   uuid.UUID `json:"application_id"`
}

func (q *Queries) SetNotificationTemplateVersion(ctx context.Context, arg SetNotificationTemplateVersionParams) error {
	_, err := q.db.Exec(ctx, setNotificationTemplateVersion, arg.ID, arg.TemplateVersion, arg.ApplicationID)
	return err
}

const unarchiveNotification = `-- name: UnarchiveNotification :one
UPDATE notifications
SET archived_at = NULL
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at
`

type UnarchiveNotificationParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) UnarchiveNotification(ctx context.Context, arg UnarchiveNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, unarchiveNotification, arg.ID, arg.ApplicationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications SET status = $3
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, template_key, template_version, notification_type, channel, recipient_user_id, recipient, payload, attachments, locale, priority, status, idempotency_key, scheduled_at, expires_at, max_retries, retry_count, sent_at, delivered_at, read_at, failed_at, created_at, updated_at, archived_at
`

type UpdateNotificationStatusParams struct {
	ID            uuid.UUID          `json:"id"`
	ApplicationID uuid.UUID          `json:"application_id"`
	Status        NotificationStatus `json:"status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationStatus, arg.ID, arg.ApplicationID, arg.Status)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.NotificationType,
		&i.Channel,
		&i.RecipientUserID,
		&i.Recipient,
		&i.Payload,
		&i.Attachments,
		&i.Locale,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.MaxRetries,
		&i.RetryCount,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
