// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSuppression(ctx context.Context, arg AddSuppressionParams) (SuppressionList, error)
	// Vacía el contenido PII (payload, recipient) de notificaciones más antiguas
	// que el periodo de retención: el del Tipo (channel_routes.pii_retention_days)
	// si lo define, o el de la aplicación como fallback.
	AnonymizeExpiredNotifications(ctx context.Context) (int64, error)
	// Derecho al olvido: anonimiza todas las notificaciones de un usuario del tenant.
	AnonymizeNotificationsByRecipient(ctx context.Context, arg AnonymizeNotificationsByRecipientParams) (int64, error)
	// Archivar es una acción del DESTINATARIO y es ortogonal al estado de entrega:
	// por eso es una columna y no un estado más (se archiva algo leído sin perder
	// que fue leído). Idempotente: re-archivar no mueve la fecha.
	ArchiveNotification(ctx context.Context, arg ArchiveNotificationParams) (Notification, error)
	// «Archivar todas las leídas» de un usuario: es la acción que de verdad limpia la
	// bandeja. Scopeada por destinatario, así nunca puede tocar las de otro.
	ArchiveReadNotificationsByUser(ctx context.Context, arg ArchiveReadNotificationsByUserParams) error
	// Cancela una notificación si aún no se ha enviado. El worker, al tomar la
	// tarea, verá CANCELLED y no enviará.
	CancelNotification(ctx context.Context, arg CancelNotificationParams) (Notification, error)
	// Conteo por (estado, ¿programada a futuro?) para derivar los estados de cola
	// del monitor (§8.3) con domain.DeriveQueueState.
	CountNotificationStates(ctx context.Context, applicationID uuid.UUID) ([]CountNotificationStatesRow, error)
	CountNotificationsByPriority(ctx context.Context, applicationID uuid.UUID) ([]CountNotificationsByPriorityRow, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	// Registra una acción del panel de administración. Se invoca dentro de la misma
	// transacción que la acción mutante (ver internal/audit). Usado desde la Fase 6.
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AdminAuditLog, error)
	CreateChannelProvider(ctx context.Context, arg CreateChannelProviderParams) (ChannelProvider, error)
	CreateChannelRoute(ctx context.Context, arg CreateChannelRouteParams) (ChannelRoute, error)
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error
	CreateRecurringSchedule(ctx context.Context, arg CreateRecurringScheduleParams) (RecurringSchedule, error)
	CreateSmtpConnection(ctx context.Context, arg CreateSmtpConnectionParams) (SmtpConnection, error)
	CreateTemplateFull(ctx context.Context, arg CreateTemplateFullParams) (Template, error)
	CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error)
	DeactivateTemplateVersions(ctx context.Context, arg DeactivateTemplateVersionsParams) error
	// Borrado real (la revocación solo la desactiva). Sirve para limpiar la lista de
	// keys revocadas, que si no se acumulan sin poder quitarlas. El handler exige que
	// la key esté ya REVOKED: así no se puede borrar por error una key en uso.
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteChannelProvider(ctx context.Context, arg DeleteChannelProviderParams) error
	DeleteChannelRoute(ctx context.Context, arg DeleteChannelRouteParams) error
	// Borrado físico de notificaciones vencidas (expires_at, fijado al crear según
	// retention_days del Tipo). Solo estados terminales; los intentos y logs caen
	// por ON DELETE CASCADE. Ahorra disco de verdad (la anonimización deja la fila).
	DeleteExpiredNotifications(ctx context.Context) (int64, error)
	DeleteRecurringSchedule(ctx context.Context, arg DeleteRecurringScheduleParams) error
	DeleteSmtpConnection(ctx context.Context, arg DeleteSmtpConnectionParams) error
	DeleteSuppression(ctx context.Context, arg DeleteSuppressionParams) error
	DeleteSuppressionByRecipient(ctx context.Context, arg DeleteSuppressionByRecipientParams) error
	// Elimina todas las versiones de una plantilla (por app, key, locale).
	DeleteTemplatesByKey(ctx context.Context, arg DeleteTemplatesByKeyParams) error
	DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error
	FinishDeliveryAttempt(ctx context.Context, arg FinishDeliveryAttemptParams) error
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	// Usada por la autenticación HMAC (Fase 2): localiza la credencial por su id
	// público para recalcular la firma.
	GetAPIKeyByKeyID(ctx context.Context, keyID string) (ApiKey, error)
	GetAdminUser(ctx context.Context, id uuid.UUID) (AdminUser, error)
	// Usada por el login del panel (Fase 2).
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetApplication(ctx context.Context, id uuid.UUID) (Application, error)
	GetApplicationBySlug(ctx context.Context, slug string) (Application, error)
	GetBaseTemplate(ctx context.Context, id uuid.UUID) (BaseTemplate, error)
	GetBaseTemplateByKey(ctx context.Context, key string) (BaseTemplate, error)
	GetChannelProvider(ctx context.Context, arg GetChannelProviderParams) (ChannelProvider, error)
	// Resuelve el "Tipo de notificación" por id (dentro de la app).
	GetChannelRouteByID(ctx context.Context, arg GetChannelRouteByIDParams) (ChannelRoute, error)
	// Resuelve el "Tipo de notificación" por su nombre único (notification_type).
	GetChannelRouteByName(ctx context.Context, arg GetChannelRouteByNameParams) (ChannelRoute, error)
	// Resuelve la última versión activa de un template para (app, key, locale).
	GetLatestActiveTemplate(ctx context.Context, arg GetLatestActiveTemplateParams) (Template, error)
	// Mayor versión existente para (app, key, locale); 0 si no hay ninguna.
	GetMaxTemplateVersion(ctx context.Context, arg GetMaxTemplateVersionParams) (int32, error)
	// Lectura con scope de tenant: SIEMPRE filtra por application_id para que un
	// tenant no pueda leer notificaciones de otro.
	GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error)
	// Lectura por el worker (proceso de confianza): no filtra por tenant porque el
	// worker opera sobre un notificationId concreto sacado de la cola.
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	// Soporta la idempotencia por tenant (Fase 3): si ya existe, se devuelve.
	GetNotificationByIdempotencyKey(ctx context.Context, arg GetNotificationByIdempotencyKeyParams) (Notification, error)
	GetRecurringSchedule(ctx context.Context, id uuid.UUID) (RecurringSchedule, error)
	GetSmtpConnection(ctx context.Context, arg GetSmtpConnectionParams) (SmtpConnection, error)
	GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error)
	GetTemplateByVersion(ctx context.Context, arg GetTemplateByVersionParams) (Template, error)
	GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (UserNotificationPreference, error)
	GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error)
	// Guardia anti-duplicado del worker: con at-least-once, una reentrega tras un
	// crash post-envío reenviaría de verdad; si ya hay un intento SUCCESS, el
	// mensaje YA llegó y solo falta marcar SENT.
	HasSuccessfulDeliveryAttempt(ctx context.Context, notificationID uuid.UUID) (bool, error)
	// Invalida todos los refresh tokens del admin (logout / revocación).
	IncrementAdminTokenVersion(ctx context.Context, id uuid.UUID) (int32, error)
	IsSuppressed(ctx context.Context, arg IsSuppressedParams) (bool, error)
	ListAPIKeysByApplication(ctx context.Context, applicationID uuid.UUID) ([]ApiKey, error)
	// Listado para el panel: una fila por template activo del tenant.
	ListActiveTemplates(ctx context.Context, applicationID uuid.UUID) ([]Template, error)
	ListActiveWebhookEndpoints(ctx context.Context, applicationID uuid.UUID) ([]WebhookEndpoint, error)
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	ListApplications(ctx context.Context) ([]Application, error)
	ListAuditLogsByApplication(ctx context.Context, arg ListAuditLogsByApplicationParams) ([]AdminAuditLog, error)
	ListBaseTemplates(ctx context.Context) ([]BaseTemplate, error)
	ListChannelProviders(ctx context.Context, applicationID uuid.UUID) ([]ChannelProvider, error)
	ListChannelRoutes(ctx context.Context, applicationID uuid.UUID) ([]ChannelRoute, error)
	ListDeliveryAttemptsByNotification(ctx context.Context, notificationID uuid.UUID) ([]DeliveryAttempt, error)
	// Usada por el PeriodicTaskManager del worker para registrar las entradas cron.
	ListEnabledRecurringSchedules(ctx context.Context) ([]RecurringSchedule, error)
	ListNotificationLogsByNotification(ctx context.Context, notificationID pgtype.UUID) ([]NotificationLog, error)
	ListNotificationsByApplication(ctx context.Context, arg ListNotificationsByApplicationParams) ([]Notification, error)
	// Listado con filtros opcionales y paginación por cursor (keyset sobre
	// created_at, id). Los filtros nulos no se aplican. Pide LIMIT+1 para saber si
	// hay más página.
	// El filtro `archived` decide qué se ve: NULL/false = solo las activas (lo que
	// pide la campana; si no, la bandeja sería una retortera), true = solo el
	// archivo.
	ListNotificationsCursor(ctx context.Context, arg ListNotificationsCursorParams) ([]Notification, error)
	ListRecurringSchedulesByApp(ctx context.Context, applicationID uuid.UUID) ([]RecurringSchedule, error)
	// Ruta(s) para (app, tipo, canal). Con el modelo 1:1 devuelve como mucho una,
	// pero se mantiene :many para no romper la resolución del procesador.
	ListRoutesForResolution(ctx context.Context, arg ListRoutesForResolutionParams) ([]ChannelRoute, error)
	ListSmtpConnections(ctx context.Context, applicationID uuid.UUID) ([]SmtpConnection, error)
	// Candidatas del reaper: PENDING/QUEUED sin transición reciente y sin
	// programación futura (huérfanas del hueco commit-luego-encolar). Compara
	// updated_at (lo refresca el trigger) para no pisar reintentos recientes.
	ListStaleNotificationsForRequeue(ctx context.Context, arg ListStaleNotificationsForRequeueParams) ([]ListStaleNotificationsForRequeueRow, error)
	// PROCESSING atascadas (crash a mitad de envío, o el mark SENT best-effort
	// falló). El reaper las reconcilia contra su último intento: SUCCESS => el
	// mensaje llegó, solo falta marcar SENT (reenviar duplicaría); si no, se
	// reencola (EnqueueSend es idempotente por TaskID).
	ListStaleProcessingForReconcile(ctx context.Context, arg ListStaleProcessingForReconcileParams) ([]ListStaleProcessingForReconcileRow, error)
	ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]SuppressionList, error)
	ListTemplateVersions(ctx context.Context, arg ListTemplateVersionsParams) ([]Template, error)
	ListWebhookEndpoints(ctx context.Context, applicationID uuid.UUID) ([]WebhookEndpoint, error)
	// Bounce/queja del proveedor: solo avanza desde SENT/DELIVERED (no pisa
	// terminales ni retrocede estados de lectura).
	MarkNotificationBounced(ctx context.Context, arg MarkNotificationBouncedParams) (int64, error)
	// Confirmación de entrega del proveedor (ingesta de eventos). Solo avanza desde
	// SENT para no pisar estados terminales (FAILED/CANCELLED) ni retroceder.
	MarkNotificationDelivered(ctx context.Context, arg MarkNotificationDeliveredParams) error
	MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error
	MarkNotificationReadByID(ctx context.Context, arg MarkNotificationReadByIDParams) (Notification, error)
	// Entre reintentos la notificación vuelve a la cola (QUEUED). El estado RETRY
	// es propio de delivery_attempts, no de la notificación (ver §3).
	MarkNotificationRetry(ctx context.Context, arg MarkNotificationRetryParams) error
	MarkNotificationSent(ctx context.Context, id uuid.UUID) error
	// Reintento manual: deja la notificación lista para reenviar (vuelve a QUEUED).
	RequeueNotification(ctx context.Context, arg RequeueNotificationParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SetAdminUserStatus(ctx context.Context, arg SetAdminUserStatusParams) (AdminUser, error)
	SetApplicationQuota(ctx context.Context, arg SetApplicationQuotaParams) (Application, error)
	SetApplicationRetention(ctx context.Context, arg SetApplicationRetentionParams) (Application, error)
	SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (Application, error)
	SetNotificationStatusByID(ctx context.Context, arg SetNotificationStatusByIDParams) error
	SetNotificationTemplateVersion(ctx context.Context, arg SetNotificationTemplateVersionParams) error
	TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	TouchAdminLastLogin(ctx context.Context, id uuid.UUID) error
	UnarchiveNotification(ctx context.Context, arg UnarchiveNotificationParams) (Notification, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error)
	// El slug es UNIQUE. Cambiarlo es seguro para los clientes HMAC (autentican por
	// key_id -> application_id, nunca por slug). Un duplicado viola la constraint y
	// el handler lo traduce a 409.
	UpdateApplicationSlug(ctx context.Context, arg UpdateApplicationSlugParams) (Application, error)
	UpdateChannelProvider(ctx context.Context, arg UpdateChannelProviderParams) (ChannelProvider, error)
	// Ajustes operables del Tipo (prioridad y retención); el resto se recrea.
	// Los NULL en retención son valores válidos (heredar / no borrar), no "sin cambio".
	UpdateChannelRouteSettings(ctx context.Context, arg UpdateChannelRouteSettingsParams) (ChannelRoute, error)
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error)
	UpdateSmtpConnection(ctx context.Context, arg UpdateSmtpConnectionParams) (SmtpConnection, error)
	UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) (UserNotificationPreference, error)
}

var _ Querier = (*Queries)(nil)
