// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_schedules.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createRecurringSchedule = `-- name: CreateRecurringSchedule :one
INSERT INTO recurring_schedules (
    application_id, name, template_key, notification_type, channel,
    recipient, recipient_user_id, payload, locale, priority, cron
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, application_id, name, template_key, notification_type, channel, recipient, recipient_user_id, payload, locale, priority, cron, enabled, created_at, updated_at
`

type CreateRecurringScheduleParams struct {
	ApplicationID    uuid.UUID       `json:"application_id"`
	Name             string          `json:"name"`
	TemplateKey      string          `json:"template_key"`
	NotificationType string          `json:"notification_type"`
	Channel          Channel         `json:"channel"`
	Recipient        json.RawMessage `json:"recipient"`
	RecipientUserID  *string         `json:"recipient_user_id"`
	Payload          json.RawMessage `json:"payload"`
	Locale           *string         `json:"locale"`
	Priority         Priority        `json:"priority"`
	Cron             string          `json:"cron"`
}

func (q *Queries) CreateRecurringSchedule(ctx context.Context, arg CreateRecurringScheduleParams) (RecurringSchedule, error) {
	row := q.db.QueryRow(ctx, createRecurringSchedule,
		arg.ApplicationID,
		arg.Name,
		arg.TemplateKey,
		arg.NotificationType,
		arg.Channel,
		arg.Recipient,
		arg.RecipientUserID,
		arg.Payload,
		arg.Locale,
		arg.Priority,
		arg.Cron,
	)
	var i RecurringSchedule
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.TemplateKey,
		&i.NotificationType,
		&i.Channel,
		&i.Recipient,
		&i.RecipientUserID,
		&i.Payload,
		&i.Locale,
		&i.Priority,
		&i.Cron,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringSchedule = `-- name: DeleteRecurringSchedule :exec
DELETE FROM recurring_schedules WHERE id = $1 AND application_id = $2
`

type DeleteRecurringScheduleParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteRecurringSchedule(ctx context.Context, arg DeleteRecurringScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringSchedule, arg.ID, arg.ApplicationID)
	return err
}

const getRecurringSchedule = `-- name: GetRecurringSchedule :one
SELECT id, application_id, name, template_key, notification_type, channel, recipient, recipient_user_id, payload, locale, priority, cron, enabled, created_at, updated_at FROM recurring_schedules WHERE id = $1
`

func (q *Queries) GetRecurringSchedule(ctx context.Context, id uuid.UUID) (RecurringSchedule, error) {
	row := q.db.QueryRow(ctx, getRecurringSchedule, id)
	var i RecurringSchedule
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.TemplateKey,
		&i.NotificationType,
		&i.Channel,
		&i.Recipient,
		&i.RecipientUserID,
		&i.Payload,
		&i.Locale,
		&i.Priority,
		&i.Cron,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRecurringSchedules = `-- name: ListEnabledRecurringSchedules :many
SELECT id, application_id, name, template_key, notification_type, channel, recipient, recipient_user_id, payload, locale, priority, cron, enabled, created_at, updated_at FROM recurring_schedules WHERE enabled = true
`

// Usada por el PeriodicTaskManager del worker para registrar las entradas cron.
func (q *Queries) ListEnabledRecurringSchedules(ctx context.Context) ([]RecurringSchedule, error) {
	rows, err := q.db.Query(ctx, listEnabledRecurringSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringSchedule
	for rows.Next() {
		var i RecurringSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.TemplateKey,
			&i.NotificationType,
			&i.Channel,
			&i.Recipient,
			&i.RecipientUserID,
			&i.Payload,
			&i.Locale,
			&i.Priority,
			&i.Cron,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringSchedulesByApp = `-- name: ListRecurringSchedulesByApp :many
SELECT id, application_id, name, template_key, notification_type, channel, recipient, recipient_user_id, payload, locale, priority, cron, enabled, created_at, updated_at FROM recurring_schedules
WHERE application_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRecurringSchedulesByApp(ctx context.Context, applicationID uuid.UUID) ([]RecurringSchedule, error) {
	rows, err := q.db.Query(ctx, listRecurringSchedulesByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringSchedule
	for rows.Next() {
		var i RecurringSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.TemplateKey,
			&i.NotificationType,
			&i.Channel,
			&i.Recipient,
			&i.RecipientUserID,
			&i.Payload,
			&i.Locale,
			&i.Priority,
			&i.Cron,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
