// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const anonymizeExpiredNotifications = `-- name: AnonymizeExpiredNotifications :execrows
UPDATE notifications n
SET payload = '{}'::jsonb, recipient = '{}'::jsonb
FROM applications a
WHERE n.application_id = a.id
  AND n.created_at < now() - make_interval(days => COALESCE(
        (SELECT cr.pii_retention_days FROM channel_routes cr
          WHERE cr.application_id = n.application_id
            AND cr.notification_type = n.notification_type),
        a.pii_retention_days))
  AND n.payload <> '{}'::jsonb
`

// Vacía el contenido PII (payload, recipient) de notificaciones más antiguas
// que el periodo de retención: el del Tipo (channel_routes.pii_retention_days)
// si lo define, o el de la aplicación como fallback.
func (q *Queries) AnonymizeExpiredNotifications(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, anonymizeExpiredNotifications)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const anonymizeNotificationsByRecipient = `-- name: AnonymizeNotificationsByRecipient :execrows
UPDATE notifications
SET payload = '{}'::jsonb, recipient = '{}'::jsonb
WHERE application_id = $1 AND recipient_user_id = $2
`

type AnonymizeNotificationsByRecipientParams struct {
	ApplicationID   uuid.UUID `json:"application_id"`
	RecipientUserID *string   `json:"recipient_user_id"`
}

// Derecho al olvido: anonimiza todas las notificaciones de un usuario del tenant.
func (q *Queries) AnonymizeNotificationsByRecipient(ctx context.Context, arg AnonymizeNotificationsByRecipientParams) (int64, error) {
	result, err := q.db.Exec(ctx, anonymizeNotificationsByRecipient, arg.ApplicationID, arg.RecipientUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredNotifications = `-- name: DeleteExpiredNotifications :execrows
DELETE FROM notifications
WHERE expires_at IS NOT NULL
  AND expires_at < now()
  AND status IN ('SENT', 'DELIVERED', 'READ', 'FAILED', 'CANCELLED')
`

// Borrado físico de notificaciones vencidas (expires_at, fijado al crear según
// retention_days del Tipo). Solo estados terminales; los intentos y logs caen
// por ON DELETE CASCADE. Ahorra disco de verdad (la anonimización deja la fila).
func (q *Queries) DeleteExpiredNotifications(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredNotifications)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
