// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smtp_connections.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSmtpConnection = `-- name: CreateSmtpConnection :one
INSERT INTO smtp_connections
    (application_id, name, host, port, username, password_enc, from_email, from_name, secure)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, application_id, name, host, port, username, password_enc, from_email, from_name, secure, status, created_at, updated_at
`

type CreateSmtpConnectionParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Name          string    `json:"name"`
	Host          string    `json:"host"`
	Port          int32     `json:"port"`
	Username      string    `json:"username"`
	PasswordEnc   []byte    `json:"password_enc"`
	FromEmail     string    `json:"from_email"`
	FromName      string    `json:"from_name"`
	Secure        bool      `json:"secure"`
}

func (q *Queries) CreateSmtpConnection(ctx context.Context, arg CreateSmtpConnectionParams) (SmtpConnection, error) {
	row := q.db.QueryRow(ctx, createSmtpConnection,
		arg.ApplicationID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEnc,
		arg.FromEmail,
		arg.FromName,
		arg.Secure,
	)
	var i SmtpConnection
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromEmail,
		&i.FromName,
		&i.Secure,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSmtpConnection = `-- name: DeleteSmtpConnection :exec
DELETE FROM smtp_connections WHERE id = $1 AND application_id = $2
`

type DeleteSmtpConnectionParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteSmtpConnection(ctx context.Context, arg DeleteSmtpConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteSmtpConnection, arg.ID, arg.ApplicationID)
	return err
}

const getSmtpConnection = `-- name: GetSmtpConnection :one
SELECT id, application_id, name, host, port, username, password_enc, from_email, from_name, secure, status, created_at, updated_at FROM smtp_connections
WHERE id = $1 AND application_id = $2
`

type GetSmtpConnectionParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) GetSmtpConnection(ctx context.Context, arg GetSmtpConnectionParams) (SmtpConnection, error) {
	row := q.db.QueryRow(ctx, getSmtpConnection, arg.ID, arg.ApplicationID)
	var i SmtpConnection
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromEmail,
		&i.FromName,
		&i.Secure,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSmtpConnections = `-- name: ListSmtpConnections :many
SELECT id, application_id, name, host, port, username, password_enc, from_email, from_name, secure, status, created_at, updated_at FROM smtp_connections
WHERE application_id = $1 ORDER BY name
`

func (q *Queries) ListSmtpConnections(ctx context.Context, applicationID uuid.UUID) ([]SmtpConnection, error) {
	rows, err := q.db.Query(ctx, listSmtpConnections, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmtpConnection
	for rows.Next() {
		var i SmtpConnection
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEnc,
			&i.FromEmail,
			&i.FromName,
			&i.Secure,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSmtpConnection = `-- name: UpdateSmtpConnection :one
UPDATE smtp_connections SET
    name = $3, host = $4, port = $5, username = $6, password_enc = $7,
    from_email = $8, from_name = $9, secure = $10, status = $11
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, name, host, port, username, password_enc, from_email, from_name, secure, status, created_at, updated_at
`

type UpdateSmtpConnectionParams struct {
	ID            uuid.UUID            `json:"id"`
	ApplicationID uuid.UUID            `json:"application_id"`
	Name          string               `json:"name"`
	Host          string               `json:"host"`
	Port          int32                `json:"port"`
	Username      string               `json:"username"`
	PasswordEnc   []byte               `json:"password_enc"`
	FromEmail     string               `json:"from_email"`
	FromName      string               `json:"from_name"`
	Secure        bool                 `json:"secure"`
	Status        StatusActiveDisabled `json:"status"`
}

func (q *Queries) UpdateSmtpConnection(ctx context.Context, arg UpdateSmtpConnectionParams) (SmtpConnection, error) {
	row := q.db.QueryRow(ctx, updateSmtpConnection,
		arg.ID,
		arg.ApplicationID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEnc,
		arg.FromEmail,
		arg.FromName,
		arg.Secure,
		arg.Status,
	)
	var i SmtpConnection
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromEmail,
		&i.FromName,
		&i.Secure,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
