// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppression_list.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addSuppression = `-- name: AddSuppression :one
INSERT INTO suppression_list (application_id, channel, recipient, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (application_id, channel, recipient) DO UPDATE SET reason = EXCLUDED.reason
RETURNING id, application_id, channel, recipient, reason, created_at
`

type AddSuppressionParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Channel       Channel   `json:"channel"`
	Recipient     string    `json:"recipient"`
	Reason        string    `json:"reason"`
}

func (q *Queries) AddSuppression(ctx context.Context, arg AddSuppressionParams) (SuppressionList, error) {
	row := q.db.QueryRow(ctx, addSuppression,
		arg.ApplicationID,
		arg.Channel,
		arg.Recipient,
		arg.Reason,
	)
	var i SuppressionList
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Channel,
		&i.Recipient,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppression = `-- name: DeleteSuppression :exec
DELETE FROM suppression_list WHERE id = $1 AND application_id = $2
`

type DeleteSuppressionParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteSuppression(ctx context.Context, arg DeleteSuppressionParams) error {
	_, err := q.db.Exec(ctx, deleteSuppression, arg.ID, arg.ApplicationID)
	return err
}

const deleteSuppressionByRecipient = `-- name: DeleteSuppressionByRecipient :exec
DELETE FROM suppression_list WHERE application_id = $1 AND channel = $2 AND recipient = $3
`

type DeleteSuppressionByRecipientParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Channel       Channel   `json:"channel"`
	Recipient     string    `json:"recipient"`
}

func (q *Queries) DeleteSuppressionByRecipient(ctx context.Context, arg DeleteSuppressionByRecipientParams) error {
	_, err := q.db.Exec(ctx, deleteSuppressionByRecipient, arg.ApplicationID, arg.Channel, arg.Recipient)
	return err
}

const isSuppressed = `-- name: IsSuppressed :one
SELECT EXISTS (
    SELECT 1 FROM suppression_list
    WHERE application_id = $1 AND channel = $2 AND recipient = $3
)
`

type IsSuppressedParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Channel       Channel   `json:"channel"`
	Recipient     string    `json:"recipient"`
}

func (q *Queries) IsSuppressed(ctx context.Context, arg IsSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSuppressed, arg.ApplicationID, arg.Channel, arg.Recipient)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSuppressions = `-- name: ListSuppressions :many
SELECT id, application_id, channel, recipient, reason, created_at FROM suppression_list
WHERE application_id = $1 ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSuppressionsParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]SuppressionList, error) {
	rows, err := q.db.Query(ctx, listSuppressions, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressionList
	for rows.Next() {
		var i SuppressionList
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Channel,
			&i.Recipient,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
