// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplateFull = `-- name: CreateTemplateFull :one
INSERT INTO templates (
    application_id, key, channel, base_template_id, name, description,
    subject, structure, body, required_variables, locale, version, kind, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, true
)
RETURNING id, application_id, key, channel, base_template_id, name, description, subject, structure, body, required_variables, locale, version, is_active, created_at, updated_at, kind
`

type CreateTemplateFullParams struct {
	ApplicationID     uuid.UUID       `json:"application_id"`
	Key               string          `json:"key"`
	Channel           Channel         `json:"channel"`
	BaseTemplateID    pgtype.UUID     `json:"base_template_id"`
	Name              string          `json:"name"`
	Description       *string         `json:"description"`
	Subject           *string         `json:"subject"`
	Structure         json.RawMessage `json:"structure"`
	Body              string          `json:"body"`
	RequiredVariables []byte          `json:"required_variables"`
	Locale            string          `json:"locale"`
	Version           int32           `json:"version"`
	Kind              string          `json:"kind"`
}

func (q *Queries) CreateTemplateFull(ctx context.Context, arg CreateTemplateFullParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplateFull,
		arg.ApplicationID,
		arg.Key,
		arg.Channel,
		arg.BaseTemplateID,
		arg.Name,
		arg.Description,
		arg.Subject,
		arg.Structure,
		arg.Body,
		arg.RequiredVariables,
		arg.Locale,
		arg.Version,
		arg.Kind,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Channel,
		&i.BaseTemplateID,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.Structure,
		&i.Body,
		&i.RequiredVariables,
		&i.Locale,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
	)
	return i, err
}

const deactivateTemplateVersions = `-- name: DeactivateTemplateVersions :exec
UPDATE templates SET is_active = false
WHERE application_id = $1 AND key = $2 AND locale = $3
`

type DeactivateTemplateVersionsParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Key           string    `json:"key"`
	Locale        string    `json:"locale"`
}

func (q *Queries) DeactivateTemplateVersions(ctx context.Context, arg DeactivateTemplateVersionsParams) error {
	_, err := q.db.Exec(ctx, deactivateTemplateVersions, arg.ApplicationID, arg.Key, arg.Locale)
	return err
}

const deleteTemplatesByKey = `-- name: DeleteTemplatesByKey :exec
DELETE FROM templates WHERE application_id = $1 AND key = $2 AND locale = $3
`

type DeleteTemplatesByKeyParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Key           string    `json:"key"`
	Locale        string    `json:"locale"`
}

// Elimina todas las versiones de una plantilla (por app, key, locale).
func (q *Queries) DeleteTemplatesByKey(ctx context.Context, arg DeleteTemplatesByKeyParams) error {
	_, err := q.db.Exec(ctx, deleteTemplatesByKey, arg.ApplicationID, arg.Key, arg.Locale)
	return err
}

const getLatestActiveTemplate = `-- name: GetLatestActiveTemplate :one
SELECT id, application_id, key, channel, base_template_id, name, description, subject, structure, body, required_variables, locale, version, is_active, created_at, updated_at, kind FROM templates
WHERE application_id = $1 AND key = $2 AND locale = $3 AND is_active = true
ORDER BY version DESC
LIMIT 1
`

type GetLatestActiveTemplateParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Key           string    `json:"key"`
	Locale        string    `json:"locale"`
}

// Resuelve la última versión activa de un template para (app, key, locale).
func (q *Queries) GetLatestActiveTemplate(ctx context.Context, arg GetLatestActiveTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, getLatestActiveTemplate, arg.ApplicationID, arg.Key, arg.Locale)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Channel,
		&i.BaseTemplateID,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.Structure,
		&i.Body,
		&i.RequiredVariables,
		&i.Locale,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
	)
	return i, err
}

const getMaxTemplateVersion = `-- name: GetMaxTemplateVersion :one
SELECT COALESCE(MAX(version), 0)::int AS max_version
FROM templates
WHERE application_id = $1 AND key = $2 AND locale = $3
`

type GetMaxTemplateVersionParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Key           string    `json:"key"`
	Locale        string    `json:"locale"`
}

// Mayor versión existente para (app, key, locale); 0 si no hay ninguna.
func (q *Queries) GetMaxTemplateVersion(ctx context.Context, arg GetMaxTemplateVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxTemplateVersion, arg.ApplicationID, arg.Key, arg.Locale)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, application_id, key, channel, base_template_id, name, description, subject, structure, body, required_variables, locale, version, is_active, created_at, updated_at, kind FROM templates WHERE id = $1 AND application_id = $2
`

type GetTemplateByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID, arg.ApplicationID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Channel,
		&i.BaseTemplateID,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.Structure,
		&i.Body,
		&i.RequiredVariables,
		&i.Locale,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
	)
	return i, err
}

const getTemplateByVersion = `-- name: GetTemplateByVersion :one
SELECT id, application_id, key, channel, base_template_id, name, description, subject, structure, body, required_variables, locale, version, is_active, created_at, updated_at, kind FROM templates
WHERE application_id = $1 AND key = $2 AND locale = $3 AND version = $4
`

type GetTemplateByVersionParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Key           string    `json:"key"`
	Locale        string    `json:"locale"`
	Version       int32     `json:"version"`
}

func (q *Queries) GetTemplateByVersion(ctx context.Context, arg GetTemplateByVersionParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByVersion,
		arg.ApplicationID,
		arg.Key,
		arg.Locale,
		arg.Version,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Channel,
		&i.BaseTemplateID,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.Structure,
		&i.Body,
		&i.RequiredVariables,
		&i.Locale,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
	)
	return i, err
}

const listActiveTemplates = `-- name: ListActiveTemplates :many
SELECT id, application_id, key, channel, base_template_id, name, description, subject, structure, body, required_variables, locale, version, is_active, created_at, updated_at, kind FROM templates
WHERE application_id = $1 AND is_active = true
ORDER BY key, locale
`

// Listado para el panel: una fila por template activo del tenant.
func (q *Queries) ListActiveTemplates(ctx context.Context, applicationID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listActiveTemplates, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Key,
			&i.Channel,
			&i.BaseTemplateID,
			&i.Name,
			&i.Description,
			&i.Subject,
			&i.Structure,
			&i.Body,
			&i.RequiredVariables,
			&i.Locale,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateVersions = `-- name: ListTemplateVersions :many
SELECT id, application_id, key, channel, base_template_id, name, description, subject, structure, body, required_variables, locale, version, is_active, created_at, updated_at, kind FROM templates
WHERE application_id = $1 AND key = $2 AND locale = $3
ORDER BY version DESC
`

type ListTemplateVersionsParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Key           string    `json:"key"`
	Locale        string    `json:"locale"`
}

func (q *Queries) ListTemplateVersions(ctx context.Context, arg ListTemplateVersionsParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplateVersions, arg.ApplicationID, arg.Key, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Key,
			&i.Channel,
			&i.BaseTemplateID,
			&i.Name,
			&i.Description,
			&i.Subject,
			&i.Structure,
			&i.Body,
			&i.RequiredVariables,
			&i.Locale,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
