// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_notification_preferences.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserPreference = `-- name: GetUserPreference :one
SELECT id, application_id, user_id, email_enabled, push_enabled, sms_enabled, in_app_enabled, created_at, updated_at FROM user_notification_preferences
WHERE application_id = $1 AND user_id = $2
`

type GetUserPreferenceParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        string    `json:"user_id"`
}

func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (UserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreference, arg.ApplicationID, arg.UserID)
	var i UserNotificationPreference
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.SmsEnabled,
		&i.InAppEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreference = `-- name: UpsertUserPreference :one
INSERT INTO user_notification_preferences
    (application_id, user_id, email_enabled, push_enabled, sms_enabled, in_app_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (application_id, user_id) DO UPDATE SET
    email_enabled  = EXCLUDED.email_enabled,
    push_enabled   = EXCLUDED.push_enabled,
    sms_enabled    = EXCLUDED.sms_enabled,
    in_app_enabled = EXCLUDED.in_app_enabled
RETURNING id, application_id, user_id, email_enabled, push_enabled, sms_enabled, in_app_enabled, created_at, updated_at
`

type UpsertUserPreferenceParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        string    `json:"user_id"`
	EmailEnabled  bool      `json:"email_enabled"`
	PushEnabled   bool      `json:"push_enabled"`
	SmsEnabled    bool      `json:"sms_enabled"`
	InAppEnabled  bool      `json:"in_app_enabled"`
}

func (q *Queries) UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) (UserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreference,
		arg.ApplicationID,
		arg.UserID,
		arg.EmailEnabled,
		arg.PushEnabled,
		arg.SmsEnabled,
		arg.InAppEnabled,
	)
	var i UserNotificationPreference
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.SmsEnabled,
		&i.InAppEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
