// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_endpoints.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (application_id, url, secret_enc, events)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, url, secret_enc, events, status, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	Url           string    `json:"url"`
	SecretEnc     []byte    `json:"secret_enc"`
	Events        []string  `json:"events"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ApplicationID,
		arg.Url,
		arg.SecretEnc,
		arg.Events,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = $1 AND application_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.ApplicationID)
	return err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, application_id, url, secret_enc, events, status, created_at, updated_at FROM webhook_endpoints
WHERE id = $1 AND application_id = $2
`

type GetWebhookEndpointParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, arg.ID, arg.ApplicationID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhookEndpoints = `-- name: ListActiveWebhookEndpoints :many
SELECT id, application_id, url, secret_enc, events, status, created_at, updated_at FROM webhook_endpoints
WHERE application_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) ListActiveWebhookEndpoints(ctx context.Context, applicationID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookEndpoints, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Url,
			&i.SecretEnc,
			&i.Events,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, application_id, url, secret_enc, events, status, created_at, updated_at FROM webhook_endpoints
WHERE application_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, applicationID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Url,
			&i.SecretEnc,
			&i.Events,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
